# Generated by Django 2.0.7 on 2018-07-18 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0002_auto_20180718_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('calories', models.IntegerField(default=0)),
                ('description', models.TextField(max_length=200)),
                ('groupWith', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='life.Group')),
            ],
        ),
    ]
