# Generated by Django 2.0.7 on 2018-07-24 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0004_auto_20180722_0710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='friends',
            new_name='participants',
        ),
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_user_friends_+', to='life.User'),
        ),
    ]
